from __future__ import annotations

"""Backward-compatible exports for AI provider modules.

This module intentionally re-exports symbols that were historically defined in
`ai.provider`, while implementation is split across smaller modules.
"""

from .base import (
    AIProvider,
    PARSE_ERROR_TYPE_PARSE,
    PARSE_ERROR_TYPE_UNAVAILABLE,
    get_rule_parse_fallback,
    infer_decree_type_from_topic,
    parse_error,
    set_rule_parse_fallback,
)
from .factory import get_provider
from .fallbacks import (
    DIPLOMACY_KEYWORDS,
    EXECUTION_PREFIX_RE,
    EXECUTION_SUFFIX_RE,
    KEYWORD_MAP,
    NEGATION_KEYWORDS,
    NARRATIVE_TEMPLATES,
    PERSON_PATTERN,
    REGION_KEYWORDS,
    REJECTION_TEMPLATES,
    rule_chat_query,
    rule_classify_chat_intent,
    rule_classify_script_choice,
    rule_minister_dialogue,
    rule_parse_free_input,
    rule_process_freeform,
    rule_script_trigger_decisions,
    template_action_implications,
    template_assembly_debate,
    template_memorial,
    template_minister_reaction,
    template_narrative,
    template_rejection,
    template_turn_commentary,
)
from .parsers import (
    DEBATE_SYSTEM_PROMPT,
    SCRIPT_CHOICE_CLASSIFICATION_SYSTEM_PROMPT,
    SCRIPT_TRIGGER_SELECTION_SYSTEM_PROMPT,
    _FREEFORM_SYSTEM_PROMPT,
    _validate_decrees,
    build_debate_prompt,
    build_freeform_user_prompt,
    build_script_choice_classification_prompt,
    build_script_trigger_selection_prompt,
    extract_json_object_text,
    parse_debate_response,
    parse_decree_response,
    parse_freeform_response,
    parse_memorial_draft,
    parse_script_choice_classification_response,
    parse_script_trigger_selection_response,
    validate_memorial_decrees,
)
from .resilient import ResilientProvider

_rule_parse_fallback_enabled = get_rule_parse_fallback()

__all__ = [
    "AIProvider",
    "DEBATE_SYSTEM_PROMPT",
    "DIPLOMACY_KEYWORDS",
    "EXECUTION_PREFIX_RE",
    "EXECUTION_SUFFIX_RE",
    "KEYWORD_MAP",
    "NARRATIVE_TEMPLATES",
    "NEGATION_KEYWORDS",
    "PARSE_ERROR_TYPE_PARSE",
    "PARSE_ERROR_TYPE_UNAVAILABLE",
    "PERSON_PATTERN",
    "REGION_KEYWORDS",
    "REJECTION_TEMPLATES",
    "ResilientProvider",
    "rule_chat_query",
    "rule_classify_chat_intent",
    "rule_classify_script_choice",
    "rule_minister_dialogue",
    "rule_parse_free_input",
    "rule_process_freeform",
    "rule_script_trigger_decisions",
    "template_action_implications",
    "template_assembly_debate",
    "template_memorial",
    "template_minister_reaction",
    "template_narrative",
    "template_rejection",
    "template_turn_commentary",
    "SCRIPT_CHOICE_CLASSIFICATION_SYSTEM_PROMPT",
    "SCRIPT_TRIGGER_SELECTION_SYSTEM_PROMPT",
    "_FREEFORM_SYSTEM_PROMPT",
    "_rule_parse_fallback_enabled",
    "_validate_decrees",
    "build_debate_prompt",
    "build_freeform_user_prompt",
    "build_script_choice_classification_prompt",
    "build_script_trigger_selection_prompt",
    "extract_json_object_text",
    "get_provider",
    "get_rule_parse_fallback",
    "infer_decree_type_from_topic",
    "parse_debate_response",
    "parse_decree_response",
    "parse_error",
    "parse_freeform_response",
    "parse_memorial_draft",
    "parse_script_choice_classification_response",
    "parse_script_trigger_selection_response",
    "set_rule_parse_fallback",
    "validate_memorial_decrees",
]
