/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/game/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Game */
        post: operations["new_game_api_game_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Decree */
        post: operations["execute_decree_api_decree_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decree/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Decree Stream */
        post: operations["execute_decree_stream_api_decree_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advance-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Month Endpoint */
        post: operations["advance_month_endpoint_api_advance_month_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decree/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Decree */
        post: operations["parse_decree_api_decree_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debate/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Debate */
        post: operations["start_debate_api_debate_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debate/silence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Silence Debate */
        post: operations["silence_debate_api_debate_silence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ministers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ministers */
        get: operations["get_ministers_api_ministers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Positions
         * @description Return all positions from PositionRegistry with category, weight, unique.
         *
         *     Optional query param `category` filters by PositionCategory (CORE, SECONDARY, NOBLE, EUNUCH).
         */
        get: operations["get_positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memorial/{memorial_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Memorial */
        post: operations["resolve_memorial_api_memorial__memorial_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minister/{minister_name}/dialogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Minister Dialogue */
        post: operations["minister_dialogue_api_minister__minister_name__dialogue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save */
        post: operations["save_api_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Saves */
        get: operations["get_saves_api_saves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/load/{save_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load */
        post: operations["load_api_load__save_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/save/{save_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Save */
        delete: operations["remove_save_api_save__save_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        /** Update Settings */
        post: operations["update_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Settings */
        get: operations["get_ai_settings_api_settings_ai_get"];
        put?: never;
        /** Update Ai Settings */
        post: operations["update_ai_settings_api_settings_ai_post"];
        /** Delete Ai Settings */
        delete: operations["delete_ai_settings_api_settings_ai_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List Ai Models */
        post: operations["list_ai_models_api_settings_ai_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assembly/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assembly Start */
        post: operations["assembly_start_api_assembly_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assembly/petition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assembly Petition */
        post: operations["assembly_petition_api_assembly_petition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assembly/debate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assembly Debate */
        post: operations["assembly_debate_api_assembly_debate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assembly/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assembly Vote */
        post: operations["assembly_vote_api_assembly_vote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assembly/decree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assembly Decree */
        post: operations["assembly_decree_api_assembly_decree_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assembly/rage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assembly Rage */
        post: operations["assembly_rage_api_assembly_rage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/court-assembly/convene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convene Assembly */
        post: operations["convene_assembly_api_court_assembly_convene_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/court-assembly/adopt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adopt Suggestion */
        post: operations["adopt_suggestion_api_court_assembly_adopt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/court-assembly/silence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Silence Assembly */
        post: operations["silence_assembly_api_court_assembly_silence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Admin */
        get: operations["verify_admin_api_admin_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ministers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Ministers */
        get: operations["admin_get_ministers_api_admin_ministers_get"];
        put?: never;
        /** Admin Create Minister */
        post: operations["admin_create_minister_api_admin_ministers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ministers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Minister */
        get: operations["admin_get_minister_api_admin_ministers__name__get"];
        /** Admin Update Minister */
        put: operations["admin_update_minister_api_admin_ministers__name__put"];
        post?: never;
        /** Admin Delete Minister */
        delete: operations["admin_delete_minister_api_admin_ministers__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Events */
        get: operations["admin_get_events_api_admin_events_get"];
        put?: never;
        /** Admin Create Event */
        post: operations["admin_create_event_api_admin_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events/{script_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Event */
        get: operations["admin_get_event_api_admin_events__script_id__get"];
        /** Admin Update Event */
        put: operations["admin_update_event_api_admin_events__script_id__put"];
        post?: never;
        /** Admin Delete Event */
        delete: operations["admin_delete_event_api_admin_events__script_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Positions */
        get: operations["admin_get_positions_api_admin_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Export */
        get: operations["admin_export_api_admin_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/import/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Import Validate */
        post: operations["admin_import_validate_api_admin_import_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Import */
        post: operations["admin_import_api_admin_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AIModelListRequest */
        AIModelListRequest: {
            /** Provider */
            provider?: string | null;
            /** Provider Type */
            provider_type?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** AISettingsRequest */
        AISettingsRequest: {
            /** Provider */
            provider: string;
            /** Provider Type */
            provider_type?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model?: string | null;
            /** Simple Model */
            simple_model?: string | null;
            /** Enable Thinking */
            enable_thinking?: boolean | null;
            /** Enable Thinking Simple */
            enable_thinking_simple?: boolean | null;
            /** Thinking Config */
            thinking_config?: {
                [key: string]: string | boolean | number;
            } | null;
            /** Thinking Config Simple */
            thinking_config_simple?: {
                [key: string]: string | boolean | number;
            } | null;
        };
        /** AdoptSuggestionRequest */
        AdoptSuggestionRequest: {
            /** Suggestion Index */
            suggestion_index: number;
        };
        /** AdvanceMonthResponse */
        AdvanceMonthResponse: {
            state: components["schemas"]["GameState"];
            /** Triggered Events */
            triggered_events?: string[];
            /** Game Over */
            game_over?: {
                [key: string]: unknown;
            } | null;
            /** New Ministers */
            new_ministers?: components["schemas"]["Minister"][];
        };
        /** AssemblyDebateRequest */
        AssemblyDebateRequest: {
            /** Topic */
            topic: string;
            /** Decree Type */
            decree_type?: string | null;
        };
        /** AssemblyDecreeRequest */
        AssemblyDecreeRequest: {
            /** Decision */
            decision: string;
        };
        /** AssemblyParticipant */
        AssemblyParticipant: {
            /** Name */
            name: string;
            /** Faction */
            faction: string;
            /** Position */
            position: string;
            /** Argument Text */
            argument_text: string;
        };
        /** AssemblyPetition */
        AssemblyPetition: {
            /** Minister Name */
            minister_name: string;
            /** Content */
            content: string;
            /**
             * Urgency
             * @default 中
             * @enum {string}
             */
            urgency: "高" | "中" | "低";
        };
        /**
         * AssemblyPhase
         * @enum {string}
         */
        AssemblyPhase: "idle" | "petition" | "debate" | "vote" | "decree";
        /** AssemblyRageRequest */
        AssemblyRageRequest: {
            /** Target Faction */
            target_faction: string;
        };
        /** AssemblySpeech */
        AssemblySpeech: {
            /** Minister Name */
            minister_name: string;
            /** Faction */
            faction: string;
            /** Content */
            content: string;
            /**
             * Stance
             * @default 中立
             * @enum {string}
             */
            stance: "赞成" | "反对" | "中立";
        };
        /** AssemblyVote */
        AssemblyVote: {
            /** Minister Name */
            minister_name: string;
            /**
             * Vote
             * @default 弃权
             * @enum {string}
             */
            vote: "赞成" | "反对" | "弃权";
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** AssemblyVoteRequest */
        AssemblyVoteRequest: {
            /** Decree Type */
            decree_type?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /** ConveneAssemblyRequest */
        ConveneAssemblyRequest: {
            /** Topic */
            topic: string;
            /** Decree Type */
            decree_type: string;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Timestamp */
            timestamp: string;
        };
        /** CourtAssembly */
        CourtAssembly: {
            /** @default idle */
            phase: components["schemas"]["AssemblyPhase"];
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Current Topic
             * @default
             */
            current_topic: string;
            decree_type?: components["schemas"]["DecreeType"] | null;
            /** Participants */
            participants?: components["schemas"]["AssemblyParticipant"][];
            /** Petitions */
            petitions?: components["schemas"]["AssemblyPetition"][];
            /** Speeches */
            speeches?: components["schemas"]["AssemblySpeech"][];
            /** Votes */
            votes?: components["schemas"]["AssemblyVote"][];
            /** Suggestions */
            suggestions?: components["schemas"]["PolicySuggestion"][];
            /**
             * Debate Text
             * @default
             */
            debate_text: string;
            /**
             * Consensus
             * @default
             */
            consensus: string;
            /**
             * Silenced
             * @default false
             */
            silenced: boolean;
            /**
             * Rage Used
             * @default false
             */
            rage_used: boolean;
            /** Silenced Factions */
            silenced_factions?: string[];
            /** Final Decision */
            final_decision?: string | null;
        };
        /** DebateMinister */
        DebateMinister: {
            /** Name */
            name: string;
            /** Faction */
            faction: string;
            /** Position Summary */
            position_summary: string;
        };
        /** DebateResult */
        DebateResult: {
            /** Debate Text */
            debate_text: string;
            minister_a: components["schemas"]["DebateMinister"];
            minister_b: components["schemas"]["DebateMinister"];
            option_a: components["schemas"]["StructuredDecree"];
            option_b: components["schemas"]["StructuredDecree"];
            /** Keywords */
            keywords?: string[];
        };
        /** DebateSilenceResponse */
        DebateSilenceResponse: {
            state: components["schemas"]["GameState"];
            /** Prestige Change */
            prestige_change: number;
        };
        /** DebateStartRequest */
        DebateStartRequest: {
            /** Category */
            category: string;
            /** Topic */
            topic: string;
        };
        /** DecreeRequest */
        DecreeRequest: {
            /** Decrees */
            decrees?: components["schemas"]["StructuredDecree"][];
            /** Free Text */
            free_text?: string | null;
            /** Source Script Id */
            source_script_id?: string | null;
            /** Loyalty Effects */
            loyalty_effects?: [
                string,
                number
            ][] | null;
            /** State Effects */
            state_effects?: {
                [key: string]: number;
            } | null;
        };
        /** DecreeResponse */
        DecreeResponse: {
            state: components["schemas"]["GameState"];
            /** Delta */
            delta?: {
                [key: string]: unknown;
            };
            /** Attribution */
            attribution?: {
                [key: string]: unknown;
            };
            /**
             * Narrative
             * @default
             */
            narrative: string;
            /** Newly Triggered Events */
            newly_triggered_events?: string[];
            game_time?: components["schemas"]["GameTime"];
            /** Game Over */
            game_over?: {
                [key: string]: unknown;
            } | null;
            /** Minister Reactions */
            minister_reactions?: components["schemas"]["MinisterReaction"][];
            turn_summary?: components["schemas"]["TurnSummary"] | null;
            /** Memorial Triggers */
            memorial_triggers?: components["schemas"]["Memorial"][];
        };
        /**
         * DecreeType
         * @enum {string}
         */
        DecreeType: "tax_increase" | "tax_decrease" | "recruit_troops" | "disband_troops" | "personnel" | "diplomacy" | "disaster_relief" | "harsh_punishment";
        /** DialogueRequest */
        DialogueRequest: {
            /** Message */
            message: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** DialogueResponse */
        DialogueResponse: {
            /** Reply */
            reply: string;
            /** Loyalty Change */
            loyalty_change: number;
            /**
             * Mood
             * @enum {string}
             */
            mood: "support" | "neutral" | "oppose";
            /** Conversation Id */
            conversation_id: string;
            state: components["schemas"]["GameState"];
        };
        /** EventChoice */
        EventChoice: {
            /** Label */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Decrees */
            decrees?: components["schemas"]["StructuredDecree"][];
            /** Loyalty Effects */
            loyalty_effects?: [
                string,
                number
            ][];
            /** State Effects */
            state_effects?: {
                [key: string]: number;
            };
        };
        /**
         * EventUrgency
         * @enum {string}
         */
        EventUrgency: "高" | "中" | "低";
        /** Faction */
        Faction: {
            /** Name */
            name: string;
            /** Satisfaction */
            satisfaction: number;
            /** Influence */
            influence: number;
            /** Rebellion Risk */
            rebellion_risk: number;
        };
        /** FactionChange */
        FactionChange: {
            /** Name */
            name: string;
            /** Satisfaction Before */
            satisfaction_before: number;
            /** Satisfaction After */
            satisfaction_after: number;
            /** Rebellion Risk Before */
            rebellion_risk_before: number;
            /** Rebellion Risk After */
            rebellion_risk_after: number;
        };
        /** GameEvent */
        GameEvent: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default 低 */
            urgency: components["schemas"]["EventUrgency"];
            /**
             * Triggered Year
             * @default 0
             */
            triggered_year: number;
            /**
             * Triggered Month
             * @default 1
             */
            triggered_month: number;
            /**
             * Rich Description
             * @default
             */
            rich_description: string;
            /** Choices */
            choices?: components["schemas"]["EventChoice"][];
            /**
             * Is Scripted
             * @default false
             */
            is_scripted: boolean;
            /**
             * Is Blocking
             * @default false
             */
            is_blocking: boolean;
            /** Script Id */
            script_id?: string | null;
            /**
             * Historical Hint
             * @default
             */
            historical_hint: string;
            /**
             * Historical Basis
             * @default
             */
            historical_basis: string;
        };
        /** GameState */
        GameState: {
            time?: components["schemas"]["GameTime"];
            /**
             * National Treasury
             * @default 20
             */
            national_treasury: number;
            /**
             * Imperial Treasury
             * @default 10
             */
            imperial_treasury: number;
            /**
             * Grain
             * @default 500
             */
            grain: number;
            /**
             * Population
             * @default 15000
             */
            population: number;
            /**
             * Military Strength
             * @default 40
             */
            military_strength: number;
            /**
             * Civil Morale
             * @default 60
             */
            civil_morale: number;
            /**
             * Military Morale
             * @default 70
             */
            military_morale: number;
            /**
             * Court Prestige
             * @default 75
             */
            court_prestige: number;
            /** Factions */
            factions?: components["schemas"]["Faction"][];
            /** Regions */
            regions?: components["schemas"]["Region"][];
            /** Ministers */
            ministers?: components["schemas"]["Minister"][];
            /** Active Events */
            active_events?: components["schemas"]["GameEvent"][];
            /** History Log */
            history_log?: components["schemas"]["HistoryEntry"][];
            /**
             * Decree Count
             * @default 0
             */
            decree_count: number;
            /** Decrees This Month */
            decrees_this_month?: {
                [key: string]: boolean;
            };
            /** Event Cooldowns */
            event_cooldowns?: {
                [key: string]: number;
            };
            /** Resolved Script Ids */
            resolved_script_ids?: string[];
            /** Trigger Decisions */
            trigger_decisions?: {
                [key: string]: components["schemas"]["TriggerDecision"];
            };
            /** Memorials */
            memorials?: components["schemas"]["Memorial"][];
            /** Memorial Cooldowns */
            memorial_cooldowns?: {
                [key: string]: number;
            };
            last_assembly?: components["schemas"]["CourtAssembly"] | null;
            /** Loyalty Zero Triggered */
            loyalty_zero_triggered?: string[];
            /**
             * Last Assembly Month
             * @default 0
             */
            last_assembly_month: number;
            /**
             * Consecutive Waits
             * @default 0
             */
            consecutive_waits: number;
            /** Minister Conversations */
            minister_conversations?: {
                [key: string]: components["schemas"]["ConversationMessage"][];
            };
        };
        /** GameStateResponse */
        GameStateResponse: {
            time?: components["schemas"]["GameTime"];
            /**
             * National Treasury
             * @default 20
             */
            national_treasury: number;
            /**
             * Imperial Treasury
             * @default 10
             */
            imperial_treasury: number;
            /**
             * Grain
             * @default 500
             */
            grain: number;
            /**
             * Population
             * @default 15000
             */
            population: number;
            /**
             * Military Strength
             * @default 40
             */
            military_strength: number;
            /**
             * Civil Morale
             * @default 60
             */
            civil_morale: number;
            /**
             * Military Morale
             * @default 70
             */
            military_morale: number;
            /**
             * Court Prestige
             * @default 75
             */
            court_prestige: number;
            /** Factions */
            factions?: components["schemas"]["Faction"][];
            /** Regions */
            regions?: components["schemas"]["Region"][];
            /** Ministers */
            ministers?: components["schemas"]["Minister"][];
            /** Active Events */
            active_events?: components["schemas"]["GameEvent"][];
            /** History Log */
            history_log?: components["schemas"]["HistoryEntry"][];
            /**
             * Decree Count
             * @default 0
             */
            decree_count: number;
            /** Decrees This Month */
            decrees_this_month?: {
                [key: string]: boolean;
            };
            /** Event Cooldowns */
            event_cooldowns?: {
                [key: string]: number;
            };
            /** Resolved Script Ids */
            resolved_script_ids?: string[];
            /** Trigger Decisions */
            trigger_decisions?: {
                [key: string]: components["schemas"]["TriggerDecision"];
            };
            /** Memorials */
            memorials?: components["schemas"]["Memorial"][];
            /** Memorial Cooldowns */
            memorial_cooldowns?: {
                [key: string]: number;
            };
            last_assembly?: components["schemas"]["CourtAssembly"] | null;
            /** Loyalty Zero Triggered */
            loyalty_zero_triggered?: string[];
            /**
             * Last Assembly Month
             * @default 0
             */
            last_assembly_month: number;
            /**
             * Consecutive Waits
             * @default 0
             */
            consecutive_waits: number;
            /** Minister Conversations */
            minister_conversations?: {
                [key: string]: components["schemas"]["ConversationMessage"][];
            };
            /** History Total Count */
            history_total_count?: number | null;
        };
        /** GameTime */
        GameTime: {
            /**
             * Year
             * @default 1627
             */
            year: number;
            /**
             * Month
             * @default 1
             */
            month: number;
            /**
             * Era Name
             * @default 天启
             */
            era_name: string;
            /**
             * Era Year
             * @default 7
             */
            era_year: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Decree Type */
            decree_type: string;
            /**
             * Decree Desc
             * @default
             */
            decree_desc: string;
            /** Delta */
            delta?: {
                [key: string]: unknown;
            };
            /**
             * Narrative
             * @default
             */
            narrative: string;
        };
        /** HistoryPage */
        HistoryPage: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Entries */
            entries?: components["schemas"]["HistoryEntry"][];
        };
        /** IndicatorTrend */
        IndicatorTrend: {
            /** Name */
            name: string;
            /** Before */
            before: number;
            /** After */
            after: number;
        };
        /** Memorial */
        Memorial: {
            /** Id */
            id: string;
            /** Author Name */
            author_name: string;
            /** Author Faction */
            author_faction: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Suggested Decrees */
            suggested_decrees?: components["schemas"]["StructuredDecree"][];
            /** Trigger Reason */
            trigger_reason: string;
            /** Urgency */
            urgency: string;
            /** Created Year */
            created_year: number;
            /** Created Month */
            created_month: number;
            /** @default pending */
            status: components["schemas"]["MemorialStatus"];
            resolution_result?: components["schemas"]["MemorialResolutionResult"] | null;
        };
        /** MemorialResolutionResult */
        MemorialResolutionResult: {
            /**
             * Action
             * @enum {string}
             */
            action: "approved" | "rejected" | "deferred";
            /** Narrative */
            narrative?: string | null;
            /** Delta */
            delta?: {
                [key: string]: number;
            } | null;
            /** Minister Reactions */
            minister_reactions?: components["schemas"]["MinisterReaction"][] | null;
        };
        /** MemorialResolveRequest */
        MemorialResolveRequest: {
            /** Action */
            action: string;
        };
        /** MemorialResolveResponse */
        MemorialResolveResponse: {
            state: components["schemas"]["GameState"];
            /** Action */
            action: string;
            /** Narrative */
            narrative?: string | null;
            /** Delta */
            delta?: {
                [key: string]: unknown;
            } | null;
            /** Minister Reactions */
            minister_reactions?: components["schemas"]["MinisterReaction"][];
        };
        /**
         * MemorialStatus
         * @enum {string}
         */
        MemorialStatus: "pending" | "approved" | "rejected" | "deferred";
        /** Minister */
        Minister: {
            /** Name */
            name: string;
            /** Faction */
            faction: string;
            /** Personality Tags */
            personality_tags?: string[];
            abilities?: components["schemas"]["MinisterAbilities"];
            /** @default active */
            status: components["schemas"]["MinisterStatus"];
            /**
             * Loyalty
             * @default 50
             */
            loyalty: number;
            /** Positions */
            positions?: string[];
            /**
             * Is Eunuch
             * @default false
             */
            is_eunuch: boolean;
            /**
             * Entry Year
             * @default 1627
             */
            entry_year: number;
            /**
             * Entry Month
             * @default 8
             */
            entry_month: number;
            /**
             * Historical Note
             * @default
             */
            historical_note: string;
            /**
             * Biography
             * @default
             */
            biography: string;
            /** Major Contributions */
            major_contributions?: string[];
            current_mission?: components["schemas"]["MissionState"] | null;
        };
        /** MinisterAbilities */
        MinisterAbilities: {
            /**
             * Civil
             * @default 0
             */
            civil: number;
            /**
             * Military
             * @default 0
             */
            military: number;
            /**
             * Diplomacy
             * @default 0
             */
            diplomacy: number;
        };
        /** MinisterChange */
        MinisterChange: {
            /** Name */
            name: string;
            /** Loyalty Before */
            loyalty_before: number;
            /** Loyalty After */
            loyalty_after: number;
            /** Status Before */
            status_before: string;
            /** Status After */
            status_after: string;
        };
        /** MinisterCreate */
        MinisterCreate: {
            /** Name */
            name: string;
            /** Faction */
            faction: string;
            /** Personality Tags */
            personality_tags?: string[];
            abilities?: components["schemas"]["MinisterAbilities"];
            /** @default active */
            status: components["schemas"]["MinisterStatus"];
            /**
             * Loyalty
             * @default 50
             */
            loyalty: number;
            /** Positions */
            positions?: string[];
            /**
             * Is Eunuch
             * @default false
             */
            is_eunuch: boolean;
            /**
             * Entry Year
             * @default 1627
             */
            entry_year: number;
            /**
             * Entry Month
             * @default 8
             */
            entry_month: number;
            /**
             * Historical Note
             * @default
             */
            historical_note: string;
            /**
             * Biography
             * @default
             */
            biography: string;
            /** Major Contributions */
            major_contributions?: string[];
            current_mission?: components["schemas"]["MissionState"] | null;
        };
        /** MinisterReaction */
        MinisterReaction: {
            /** Minister Name */
            minister_name: string;
            /** Faction */
            faction: string;
            /** Reaction Type */
            reaction_type: string;
            /** Reaction Text */
            reaction_text: string;
            /** Loyalty Change */
            loyalty_change: number;
        };
        /**
         * MinisterStatus
         * @enum {string}
         */
        MinisterStatus: "active" | "idle" | "removed" | "not_yet_entered" | "on_mission";
        /** MinisterUpdate */
        MinisterUpdate: {
            /** Name */
            name: string;
            /** Faction */
            faction: string;
            /** Personality Tags */
            personality_tags?: string[];
            abilities?: components["schemas"]["MinisterAbilities"];
            /** @default active */
            status: components["schemas"]["MinisterStatus"];
            /**
             * Loyalty
             * @default 50
             */
            loyalty: number;
            /** Positions */
            positions?: string[];
            /**
             * Is Eunuch
             * @default false
             */
            is_eunuch: boolean;
            /**
             * Entry Year
             * @default 1627
             */
            entry_year: number;
            /**
             * Entry Month
             * @default 8
             */
            entry_month: number;
            /**
             * Historical Note
             * @default
             */
            historical_note: string;
            /**
             * Biography
             * @default
             */
            biography: string;
            /** Major Contributions */
            major_contributions?: string[];
            current_mission?: components["schemas"]["MissionState"] | null;
        };
        /** MissionState */
        MissionState: {
            /** Name */
            name: string;
            /**
             * Progress Months
             * @default 0
             */
            progress_months: number;
            /** Total Months */
            total_months: number;
            /** Cost */
            cost: number;
            /** Effects */
            effects?: {
                [key: string]: unknown;
            };
        };
        /** ParseRequest */
        ParseRequest: {
            /** Text */
            text: string;
        };
        /**
         * PersonnelAction
         * @enum {string}
         */
        PersonnelAction: "appoint" | "dismiss" | "execute";
        /** PolicySuggestion */
        PolicySuggestion: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            related_decree: components["schemas"]["StructuredDecree"];
            /** Supporter Names */
            supporter_names?: string[];
        };
        /** Region */
        Region: {
            /** Name */
            name: string;
            /** Stability */
            stability: number;
            /** Garrison */
            garrison: number;
            /** @default 朝廷 */
            control: components["schemas"]["RegionControl"];
            /** @default none */
            threat: components["schemas"]["RegionThreat"];
            /** @default medium */
            tax_contribution: components["schemas"]["TaxContribution"];
            /**
             * Civil Morale
             * @default 50
             */
            civil_morale: number;
            /**
             * Rebellion Risk
             * @default 10
             */
            rebellion_risk: number;
            /**
             * Tax Rate
             * @default 0.5
             */
            tax_rate: number;
            /**
             * Tax Collected
             * @default 0
             */
            tax_collected: number;
            /**
             * Disaster Level
             * @default 0
             */
            disaster_level: number;
        };
        /** RegionChange */
        RegionChange: {
            /** Name */
            name: string;
            /** Stability Before */
            stability_before: number;
            /** Stability After */
            stability_after: number;
            /** Control Before */
            control_before: string;
            /** Control After */
            control_after: string;
            /** Threat Before */
            threat_before: string;
            /** Threat After */
            threat_after: string;
            /** Garrison Before */
            garrison_before?: number | null;
            /** Garrison After */
            garrison_after?: number | null;
            /** Civil Morale Before */
            civil_morale_before?: number | null;
            /** Civil Morale After */
            civil_morale_after?: number | null;
            /** Rebellion Risk Before */
            rebellion_risk_before?: number | null;
            /** Rebellion Risk After */
            rebellion_risk_after?: number | null;
            /** Disaster Level Before */
            disaster_level_before?: number | null;
            /** Disaster Level After */
            disaster_level_after?: number | null;
            /** Tax Collected Before */
            tax_collected_before?: number | null;
            /** Tax Collected After */
            tax_collected_after?: number | null;
            /** Tax Rate Before */
            tax_rate_before?: number | null;
            /** Tax Rate After */
            tax_rate_after?: number | null;
            /** Tax Contribution Before */
            tax_contribution_before?: string | null;
            /** Tax Contribution After */
            tax_contribution_after?: string | null;
        };
        /**
         * RegionControl
         * @enum {string}
         */
        RegionControl: "朝廷" | "失控" | "沦陷";
        /** RegionDetail */
        RegionDetail: {
            /** Region */
            region: string;
            /** Field */
            field: string;
            /** Delta */
            delta: number;
            /** Source */
            source: string;
        };
        /**
         * RegionThreat
         * @enum {string}
         */
        RegionThreat: "none" | "后金" | "民变" | "土司" | "海盗";
        /** SaveRequest */
        SaveRequest: {
            /** Name */
            name?: string | null;
        };
        /** SettingsRequest */
        SettingsRequest: {
            /** Rule Parse Fallback */
            rule_parse_fallback: boolean;
        };
        /** StructuredDecree */
        StructuredDecree: {
            type: components["schemas"]["DecreeType"];
            /** Target */
            target?: string | null;
            sub_action?: components["schemas"]["PersonnelAction"] | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TaxContribution
         * @enum {string}
         */
        TaxContribution: "low" | "medium" | "high";
        /** TriggerDecision */
        TriggerDecision: {
            /** Should Trigger */
            should_trigger: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
        };
        /** TurnSummary */
        TurnSummary: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Era Name */
            era_name: string;
            /** Era Year */
            era_year: number;
            /**
             * Commentary
             * @default
             */
            commentary: string;
            /** Major Events */
            major_events?: string[];
            /** Action Implications */
            action_implications?: string[];
            /** Indicator Trends */
            indicator_trends?: components["schemas"]["IndicatorTrend"][];
            /** Faction Changes */
            faction_changes?: components["schemas"]["FactionChange"][];
            /** Region Changes */
            region_changes?: components["schemas"]["RegionChange"][];
            /** Minister Changes */
            minister_changes?: components["schemas"]["MinisterChange"][];
            /** Region Details */
            region_details?: components["schemas"]["RegionDetail"][] | null;
            /**
             * Pending Memorials Count
             * @default 0
             */
            pending_memorials_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    new_game_api_game_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
        };
    };
    execute_decree_api_decree_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecreeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecreeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_decree_stream_api_decree_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecreeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_month_endpoint_api_advance_month_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceMonthResponse"];
                };
            };
        };
    };
    parse_decree_api_decree_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredDecree"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateResponse"];
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_debate_api_debate_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebateStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    silence_debate_api_debate_silence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebateSilenceResponse"];
                };
            };
        };
    };
    get_ministers_api_ministers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Minister"][];
                };
            };
        };
    };
    get_positions_api_positions_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_memorial_api_memorial__memorial_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memorial_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorialResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorialResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    minister_dialogue_api_minister__minister_name__dialogue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minister_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_api_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saves_api_saves_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    load_api_load__save_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                save_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_save_api_save__save_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                save_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_settings_api_settings_ai_get: {
        parameters: {
            query?: {
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ai_settings_api_settings_ai_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AISettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ai_settings_api_settings_ai_delete: {
        parameters: {
            query: {
                provider: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ai_models_api_settings_ai_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIModelListRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assembly_start_api_assembly_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    assembly_petition_api_assembly_petition_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    assembly_debate_api_assembly_debate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssemblyDebateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assembly_vote_api_assembly_vote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssemblyVoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assembly_decree_api_assembly_decree_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssemblyDecreeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assembly_rage_api_assembly_rage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssemblyRageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convene_assembly_api_court_assembly_convene_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConveneAssemblyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adopt_suggestion_api_court_assembly_adopt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdoptSuggestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    silence_assembly_api_court_assembly_silence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    verify_admin_api_admin_verify_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_ministers_api_admin_ministers_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_minister_api_admin_ministers_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MinisterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_minister_api_admin_ministers__name__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_minister_api_admin_ministers__name__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MinisterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_minister_api_admin_ministers__name__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_events_api_admin_events_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_event_api_admin_events_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_event_api_admin_events__script_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path: {
                script_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_event_api_admin_events__script_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path: {
                script_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_event_api_admin_events__script_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path: {
                script_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_positions_api_admin_positions_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_export_api_admin_export_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_import_validate_api_admin_import_validate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_import_api_admin_import_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
